"""GitHub API endpoints for creating issues and PRs from scan results."""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from vulnscout.models.db import get_db
from vulnscout.models.schemas import Patch, Scan, Vulnerability
from vulnscout.utils.github_integration import create_issue as _create_issue
from vulnscout.utils.github_integration import create_pr as _create_pr

router = APIRouter()


class IssueRequest(BaseModel):
    repo: str | None = None
    severity: str | None = None


class PRRequest(BaseModel):
    repo: str | None = None
    branch: str = "vulnscout-fix"
    base: str = "main"


@router.post("/{scan_id}/issues")
async def create_issues(scan_id: str, req: IssueRequest, db: Session = Depends(get_db)):
    """Create GitHub issues for vulnerabilities in a scan."""
    scan = db.query(Scan).filter(Scan.id == scan_id).first()
    if not scan:
        raise HTTPException(404, "Scan not found")

    repo = req.repo or scan.source_path
    query = db.query(Vulnerability).filter(Vulnerability.scan_id == scan_id)
    if req.severity:
        query = query.filter(Vulnerability.severity == req.severity)
    vulns = query.all()

    results = []
    for v in vulns:
        body = (
            f"## {v.title}\n\n"
            f"- **Severity:** {v.severity}\n"
            f"- **CWE:** {v.cwe_id or 'N/A'}\n"
            f"- **File:** `{v.file_path}:{v.line_start or ''}`\n\n"
            f"### Description\n{v.description or 'No description.'}\n"
        )
        try:
            result = _create_issue(repo, f"[VulnScout] {v.title}", body)
            results.append({"vuln_id": v.id, "issue_number": result["number"], "url": result["html_url"]})
        except Exception as e:
            results.append({"vuln_id": v.id, "error": str(e)})

    return {"scan_id": scan_id, "repo": repo, "results": results}


@router.post("/{scan_id}/pr")
async def create_pull_request(scan_id: str, req: PRRequest, db: Session = Depends(get_db)):
    """Create a GitHub PR with fix patches for a scan."""
    scan = db.query(Scan).filter(Scan.id == scan_id).first()
    if not scan:
        raise HTTPException(404, "Scan not found")

    repo = req.repo or scan.source_path
    patches = (
        db.query(Patch)
        .join(Vulnerability)
        .filter(Vulnerability.scan_id == scan_id, Patch.status == "draft")
        .all()
    )

    if not patches:
        raise HTTPException(400, "No fix patches found for this scan")

    all_diffs = "\n".join(p.diff_content or "" for p in patches if p.diff_content)
    summary = "\n".join(f"- {p.vulnerability.title} ({p.vulnerability.severity})" for p in patches[:20])

    try:
        result = _create_pr(
            repo_path=repo,
            branch_name=req.branch,
            diff_content=all_diffs,
            commit_message="fix: apply VulnScout security fixes",
            pr_title=f"[VulnScout] Security fixes ({len(patches)} vulnerabilities)",
            pr_body=f"## Automated Security Fixes\n\nThis PR was automatically generated by VulnScout.\n\n{summary}",
            base_branch=req.base,
        )
        return {"scan_id": scan_id, "repo": repo, "pr_url": result.get("html_url", ""), "pr_number": result.get("number")}
    except Exception as e:
        raise HTTPException(500, f"Failed to create PR: {e}")
